<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.r.iIAiQ' shared service.

return $this->privates['.service_locator.r.iIAiQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'partenaire' => ['privates', '.errored..service_locator.r.iIAiQ.App\\Entity\\Partenaires', NULL, 'Cannot autowire service ".service_locator.r.iIAiQ": it references class "App\\Entity\\Partenaires" but no such service exists.'],
    'partenairesRepository' => ['privates', 'App\\Repository\\PartenairesRepository', 'getPartenairesRepositoryService.php', true],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
], [
    'partenaire' => 'App\\Entity\\Partenaires',
    'partenairesRepository' => 'App\\Repository\\PartenairesRepository',
    'serializer' => '?',
]);
