<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2ay5hx0\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2ay5hx0/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container2ay5hx0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container2ay5hx0\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \Container2ay5hx0\srcApp_KernelTestDebugContainer([
    'container.build_hash' => '2ay5hx0',
    'container.build_id' => 'df40975e',
    'container.build_time' => 1565111719,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2ay5hx0');
