<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security-http/AccessMapInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security-http/AccessMap.php';

$this->privates['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/api/login'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/api/Entreprise'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/api/depot'), [0 => 'ROLE_CAISSIER'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/api/AjoutCompte'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/api/partenaires'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/api/depots'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/api/AjoutCaissier'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/api/adduser'), [0 => 'ROLE_ADMIN_PART'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/api/listes'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/api/envoie'), [0 => 'ROLE_UTILISATEUR'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/api/Retrait'), [0 => 'ROLE_UTILISATEUR'], NULL);

return $instance;
