<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yzghMh0' shared service.

return $this->privates['.service_locator.yzghMh0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\SecurityController::admin' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.9cYN13S', 'get_ServiceLocator_9cYN13SService.php', true],
    'App\\Controller\\WariController::ajoutComptB' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\WariController::bloquerPartenaie' => ['privates', '.service_locator.V84UHq3', 'get_ServiceLocator_V84UHq3Service.php', true],
    'App\\Controller\\WariController::creerPartenaire' => ['privates', '.service_locator.9cYN13S', 'get_ServiceLocator_9cYN13SService.php', true],
    'App\\Controller\\WariController::depot' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\WariController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\SecurityController:admin' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.9cYN13S', 'get_ServiceLocator_9cYN13SService.php', true],
    'App\\Controller\\WariController:ajoutComptB' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\WariController:bloquerPartenaie' => ['privates', '.service_locator.V84UHq3', 'get_ServiceLocator_V84UHq3Service.php', true],
    'App\\Controller\\WariController:creerPartenaire' => ['privates', '.service_locator.9cYN13S', 'get_ServiceLocator_9cYN13SService.php', true],
    'App\\Controller\\WariController:depot' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\WariController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
], [
    'App\\Controller\\SecurityController::admin' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\WariController::ajoutComptB' => '?',
    'App\\Controller\\WariController::bloquerPartenaie' => '?',
    'App\\Controller\\WariController::creerPartenaire' => '?',
    'App\\Controller\\WariController::depot' => '?',
    'App\\Controller\\WariController::setViewHandler' => '?',
    'App\\Controller\\SecurityController:admin' => '?',
    'App\\Controller\\SecurityController:register' => '?',
    'App\\Controller\\WariController:ajoutComptB' => '?',
    'App\\Controller\\WariController:bloquerPartenaie' => '?',
    'App\\Controller\\WariController:creerPartenaire' => '?',
    'App\\Controller\\WariController:depot' => '?',
    'App\\Controller\\WariController:setViewHandler' => '?',
]);
